delete from POS_DATA_PURGE_CATEGORY;

--REM INSERTING into POS_DATA_PURGE_CATEGORY
Insert into POS_DATA_PURGE_CATEGORY (DATA_PURGE_CATEGORY_ID,DATA_PURGE_CATEGORY_NAME,POS_CRT_ON,POS_MOD_ON) values (1,'Retail Transactions',to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CATEGORY (DATA_PURGE_CATEGORY_ID,DATA_PURGE_CATEGORY_NAME,POS_CRT_ON,POS_MOD_ON) values (2,'Control Transactions',to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CATEGORY (DATA_PURGE_CATEGORY_ID,DATA_PURGE_CATEGORY_NAME,POS_CRT_ON,POS_MOD_ON) values (3,'Tender Control Transactions',to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CATEGORY (DATA_PURGE_CATEGORY_ID,DATA_PURGE_CATEGORY_NAME,POS_CRT_ON,POS_MOD_ON) values (4,'Master Data',to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CATEGORY (DATA_PURGE_CATEGORY_ID,DATA_PURGE_CATEGORY_NAME,POS_CRT_ON,POS_MOD_ON) values (5,'Promotions',to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CATEGORY (DATA_PURGE_CATEGORY_ID,DATA_PURGE_CATEGORY_NAME,POS_CRT_ON,POS_MOD_ON) values (6,'Processed Transactions Directory',to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('01-JUN-17','DD-MON-RR HH24.MI.SSXFF'));


--REM INSERTING into POS_DATA_PURGE_CONFIG

delete from POS_DATA_PURGE_CONFIG;
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (1,'BO',730,'05:00:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (2,'BO',45,'05:01:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (3,'BO',90,'05:02:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (4,'BO',45,'05:03:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (5,'BO',45,'05:04:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (2,'REG',30,'05:01:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (3,'REG',30,'05:02:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (4,'REG',45,'05:03:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (5,'REG',45,'05:04:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (1,'EC',99999,'05:00:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (2,'EC',99999,'05:01:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (3,'EC',99999,'05:02:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (4,'EC',99999,'05:03:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (5,'EC',45,'05:04:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (6,'BO',45,'05:05:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (6,'EC',99999,'05:05:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (6,'REG',30,'05:05:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));
Insert into POS_DATA_PURGE_CONFIG (DATA_PURGE_CATEGORY_ID,SERVER_TYPE,NO_OF_RNTN_DAYS,PURGE_TIME,POS_CRT_ON,POS_MOD_ON) values (1,'REG',30,'05:00:00',to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'),to_timestamp('12-JUN-17','DD-MON-RR HH24.MI.SSXFF'));

